  HOST = "158.39.163.5"
  PORT = 30002

  socket_open(HOST, PORT, "Unity")
  
  message = "Hello Unity Server from UR!"
  socket_send_string(message, "Unity")
  data = socket_read_string("Unity")
  if(data != ""):
    data_split = str_split(data)
    textmsg("X:")
    textmsg(data_split[0]) 
    textmsg("Y:")
    textmsg(data_split[1])
    textmsg("Z:")
    textmsg(data_split[2])
    tcp_pose = get_target_tcp_pose()
    # Displacement
    tcp_pose[0] = tcp_pose[0] + data_split[0]
    tcp_pose[1] = tcp_pose[1] + data_split[2]
    tcp_pose[2] = tcp_pose[2] + data_split[1]
    # Rotation
    #tcp_pose[3] = tcp_pose[3] + data_split[3]
    #tcp_pose[4] = tcp_pose[4] + data_split[4]
    #tcp_pose[5] = tcp_pose[5] + data_split[5]
    textmsg(tcp_pose)
    if(get_inverse_kin_has_solution(tcp_pose)):
      speedj(get_inverse_kin(tcp_pose), a=5)
      #movej(tcp_pose,a=5, v=5, t=0, r=0)
      #movel(tcp_pose,a=2.5, v=5, t=0, r=0)
    else:
      textmsg("No solution found")
  end
    sleep(0.01)    
  end
  socket_close("Unity")

end